const textsKompetisiNTT = {
  ID: {
    introText: {
      title: "FORMULIR PENDAFTARAN KOMPETISI FILM NTT FLOBAMORA FILM FESTIVAL 2025",
      greeting: "Halo sineas NTT! Selamat datang di Kompetisi Film NTT Flobamora Film Festival 2025. Silakan lengkapi dan unggah karya Anda.",
      filmRequirementsTitle: "Persyaratan Film:",
      filmRequirements: ["Film produksi tahun 2023–2025.", "Film karya sutradara asal atau berdomisili di Nusa Tenggara Timur.", "Durasi maksimal 30 menit.", "Kategori film: Fiksi, Dokumenter, dan Eksperimental."],
      materialsTitle: "Materi yang harus disiapkan:",
      materials: ["Link preview film dan trailer", "Subtitle (format .srt)", "Sinopsis & Pernyataan Sutradara", "Biografi dan Filmografi Sutradara", "Poster, Still Images, dan Press Kit (jika ada)"],
      closing: "Pastikan semua data dan dokumen yang Anda unggah sudah benar dan sesuai.",
      contact: "Jika ada pertanyaan, silakan hubungi kami di",
      email: "contact@flobamorafilmfestival.com",
      footerNote: "* Form ini hanya untuk kompetisi terbuka bagi sineas NTT.",
      requiredNote: "* Semua kolom wajib diisi kecuali jika disebutkan tidak wajib.",
    },

    namaPendaftar: "Nama Lengkap Pendaftar*",
    nomorKontak: "Nomor Kontak (WhatsApp)*",
    email: "Alamat Email*",
    mediaSosialSutradara: "Akun Media Sosial Sutradara",
    judulFilm: "Judul Film*",
    kategoriFilm: "Kategori Film*",
    kategoriOptions: [
      { value: "", label: "-- Pilih Kategori --" },
      { value: "fiksi", label: "Fiksi" },
      { value: "dokumenter", label: "Dokumenter" },
      { value: "eksperimental", label: "Eksperimental" },
    ],
    tahunProduksi: "Tahun Produksi*",
    durasiFilm: "Durasi Film*",
    bahasaFilm: "Bahasa yang Digunakan dalam Film*",
    subtitleLink: "Link Subtitle (.srt)*",
    sinopsis: "Sinopsis (maks. 1000 kata)*",
    pernyataanSutradara: "Pernyataan Sutradara*",
    resolusiFilm: "Resolusi Film*",
    resolusiOptions: [
      { value: "", label: "-- Pilih Resolusi --" },
      { value: "Full HD", label: "Full HD" },
      { value: "2K", label: "2K" },
      { value: "4K", label: "4K" },
    ],
    sound: "Tata Suara*",
    soundOptions: [
      { value: "", label: "-- Pilih Sound --" },
      { value: "mono", label: "Mono" },
      { value: "stereo", label: "Stereo" },
      { value: "silent", label: "Tanpa Suara" },
    ],
    warna: "Warna Film*",
    warnaOptions: [
      { value: "", label: "-- Pilih Warna --" },
      { value: "warna", label: "Berwarna" },
      { value: "hitamPutih", label: "Hitam Putih" },
    ],
    namaProduser: "Nama Lengkap Produser*",
    mediaSosialProduser: "Media Sosial Produser",
    namaRumahProduksi: "Nama Rumah Produksi / Komunitas*",
    mediaSosialProduksi: "Media Sosial Produksi / Komunitas",
    bioSutradara: "Biografi Sutradara (maks. 500 kata)*",
    filmografiSutradara: "Filmografi Sutradara (PDF)*",
    submitButton: "Kirim Formulir",
  },

  EN: {
    introText: {
      title: "NTT FILM COMPETITION REGISTRATION FORM - FLOBAMORA FILM FESTIVAL 2025",
      greeting: "Hello NTT filmmakers! Welcome to the NTT Film Competition of Flobamora Film Festival 2025. Please complete and upload your work.",
      filmRequirementsTitle: "Film Requirements:",
      filmRequirements: ["Films produced in 2023–2025.", "Films by directors from or residing in East Nusa Tenggara.", "Maximum duration: 30 minutes.", "Categories: Fiction, Documentary, and Experimental."],
      materialsTitle: "Materials to Prepare:",
      materials: ["Film preview link and trailer", "Subtitle (.srt format)", "Synopsis & Director’s Statement", "Director Biography and Filmography", "Poster, Still Images, and Press Kit (if available)"],
      closing: "Please ensure that all uploaded data and documents are correct and complete.",
      contact: "If you have any questions, please contact us at",
      email: "contact@flobamorafilmfestival.com",
      footerNote: "* This form is only for filmmakers from NTT.",
      requiredNote: "* All fields are mandatory unless otherwise stated.",
    },

    namaPendaftar: "Full Name of Submitter*",
    nomorKontak: "Phone Number (WhatsApp)*",
    email: "Email Address*",
    mediaSosialSutradara: "Director's Social Media",
    judulFilm: "Film Title*",
    kategoriFilm: "Film Category*",
    kategoriOptions: [
      { value: "", label: "-- Select Category --" },
      { value: "fiksi", label: "Fiction" },
      { value: "dokumenter", label: "Documentary" },
      { value: "eksperimental", label: "Experimental" },
    ],
    tahunProduksi: "Year of Production*",
    durasiFilm: "Film Duration*",
    bahasaFilm: "Language Used in the Film*",
    subtitleLink: "Subtitle Link (.srt)*",
    sinopsis: "Synopsis (max. 1000 words)*",
    pernyataanSutradara: "Director's Statement*",
    resolusiFilm: "Film Resolution*",
    resolusiOptions: [
      { value: "", label: "-- Select Resolution --" },
      { value: "Full HD", label: "Full HD" },
      { value: "2K", label: "2K" },
      { value: "4K", label: "4K" },
    ],
    sound: "Sound*",
    soundOptions: [
      { value: "", label: "-- Select Sound --" },
      { value: "mono", label: "Mono" },
      { value: "stereo", label: "Stereo" },
      { value: "silent", label: "Silent" },
    ],
    warna: "Color*",
    warnaOptions: [
      { value: "", label: "-- Select Color --" },
      { value: "warna", label: "Color" },
      { value: "hitamPutih", label: "Black & White" },
    ],
    namaProduser: "Producer's Full Name*",
    mediaSosialProduser: "Producer's Social Media",
    namaRumahProduksi: "Production House / Community*",
    mediaSosialProduksi: "Production House Social Media",
    bioSutradara: "Director Biography (max. 500 words)*",
    filmografiSutradara: "Director Filmography (PDF)*",
    submitButton: "Submit Form",
  },
};

export default textsKompetisiNTT;
