// initialFormData.js
const initialFormData = {
  email: "",
  posisi: "",
  namaPendaftar: "",
  nomorKontak: "",
  namaSutradara: "",
  domisiliSutradara: "",
  fotoSutradara: null,
  nomorKontakSutradara: "",
  emailSutradara: "",
  mediaSosialSutradara: "",
  bioSutradara: null,
  filmografiSutradara: null,
  namaProduser: "",
  mediaSosialProduser: "",
  namaSekolah: "",
  mediaSosialSekolah: "",
  kartuPelajar: null,
  judulFilm: "",
  kategoriFilm: "",
  tahunProduksi: "",
  durasiFilm: "",
  bahasaFilm: [],
  bahasaLain: "",
  subtitleLink: "",
  sinopsis: "",
  pernyataanSutradara: "",
  resolusiFilm: "",
  sound: "",
  warna: "",
  linkPreview: "",
  aksesPassword: "",
  linkTrailer: "",
  stillImages: [],
  posterFilm: null,
  pressKit: null,
  publikasiSetuju: false,
  publikasiFilmSetuju: false,
  dataBenarSetuju: false,
};

export default initialFormData;
