// src/utils/textsLayarNusantara.jsx

const texts = {
  ID: {
    introText: {
      title: "FORMULIR PENDAFTARAN FILM NON-KOMPETISI FLOBAMORA FILM FESTIVAL 2025",
      greeting:
        "Ayo Bergabung di Flobamora Film Festival!\nKami mengundang semua pembuat film untuk ikut serta dalam Flobamora Film Festival yang akan berlangsung pada 5 - 9 Agustus 2024! Ini adalah kesempatan emas untuk menampilkan karya-karya kreatif Anda di program Layar Nusantara.",
      filmRequirementsTitle: "Ketentuan film untuk program non-kompetisi:",
      filmRequirements: [
        "Terbuka untuk umum dan film dengan tema bebas",
        "Film berdurasi maksimal 35 menit (termasuk pembuka dan credit title)",
        "Film diproduksi dalam kurun waktu 2 tahun terakhir (2024-2025)",
        "Genre film dokumenter, fiksi, dan eksperimental",
        "Film menggunakan bahasa Indonesia. Bila menggunakan bahasa daerah atau asing, wajib mencantumkan subtitle Bahasa Indonesia yang jelas.",
        "Film tidak sedang tayang di kanal digital seperti OTT atau layanan streaming lainnya",
      ],
      materialsTitle: "",
      materials: [],
      closing: "Jika menemukan kendala dapat menghubungi kami di flobamorafilmfestival@gmail.com\n\nTerima kasih.\nSampai jumpa di Flobamora Film Festival 5 - 9 Agustus 2024\n\nFlobamora menanti karyamu!",
      contact: "Kontak: ",
      email: "flobamorafilmfestival@gmail.com",
      footerNote: "Nama, alamat email, dan foto yang terkait dengan Akun Google Anda akan direkam saat Anda mengupload file dan mengirimkan formulir ini.",
      requiredNote: "* Menunjukkan pertanyaan yang wajib diisi",
    },
    namaPendaftar: "Nama Lengkap Pendaftar*",
    nomorKontak: "Nomor Kontak (WhatsApp)*",
    email: "Alamat Email*",
    mediaSosialSutradara: "Akun Media Sosial Sutradara",
    judulFilm: "Judul Film*",
    kategoriFilm: "Kategori Film*",
    kategoriOptions: [
      { value: "", label: "-- Pilih Kategori --" },
      { value: "fiksi", label: "Fiksi" },
      { value: "dokumenter", label: "Dokumenter" },
      { value: "eksperimental", label: "Eksperimental" },
    ],
    tahunProduksi: "Tahun Produksi*",
    durasiFilm: "Durasi Film*",
    bahasaFilm: "Bahasa yang Digunakan dalam Film*",
    subtitleLink: "Link Subtitle (.srt)*",
    sinopsis: "Sinopsis (maks. 1000 kata)*",
    pernyataanSutradara: "Pernyataan Sutradara*",
    resolusiFilm: "Resolusi Film*",
    resolusiOptions: [
      { value: "", label: "-- Pilih Resolusi --" },
      { value: "Full HD", label: "Full HD" },
      { value: "2K", label: "2K" },
      { value: "4K", label: "4K" },
    ],
    sound: "Tata Suara*",
    soundOptions: [
      { value: "", label: "-- Pilih Sound --" },
      { value: "mono", label: "Mono" },
      { value: "stereo", label: "Stereo" },
      { value: "silent", label: "Tanpa Suara" },
    ],
    warna: "Warna Film*",
    warnaOptions: [
      { value: "", label: "-- Pilih Warna --" },
      { value: "warna", label: "Berwarna" },
      { value: "hitamPutih", label: "Hitam Putih" },
    ],
    namaProduser: "Nama Lengkap Produser*",
    mediaSosialProduser: "Media Sosial Produser",
    namaRumahProduksi: "Nama Rumah Produksi / Komunitas*",
    mediaSosialProduksi: "Media Sosial Produksi / Komunitas",
    bioSutradara: "Biografi Sutradara (maks. 500 kata)*",
    filmografiSutradara: "Filmografi Sutradara (PDF)*",
    submitButton: "Kirim Formulir",
  },
  EN: {
    introText: {
      title: "NON-COMPETITION FILM SUBMISSION FORM - FLOBAMORA FILM FESTIVAL 2025",
      greeting:
        "Join us at Flobamora Film Festival!\nWe invite all filmmakers to take part in the Flobamora Film Festival happening from August 5 – 9, 2024! This is a golden opportunity to showcase your creative works in the Layar Nusantara program.",
      filmRequirementsTitle: "Non-competition film program requirements:",
      filmRequirements: [
        "Open to the public with no theme restrictions",
        "Maximum film duration of 35 minutes (including opening and credits)",
        "Films produced within the last 2 years (2024-2025)",
        "Acceptable genres: documentary, fiction, and experimental",
        "Films must be in Indonesian. If in a regional or foreign language, clear Indonesian subtitles are required.",
        "Films must not be currently available on digital platforms like OTT or streaming services",
      ],
      materialsTitle: "",
      materials: [],
      closing: "If you encounter any issues, please contact us at flobamorafilmfestival@gmail.com\n\nThank you.\nSee you at Flobamora Film Festival, August 5–9, 2024\n\nFlobamora awaits your film!",
      contact: "Contact: ",
      email: "flobamorafilmfestival@gmail.com",
      footerNote: "Your name, email address, and photo associated with your Google Account will be recorded when you upload files and submit this form.",
      requiredNote: "* Indicates required fields",
    },
    namaPendaftar: "Full Name of Submitter*",
    nomorKontak: "Phone Number (WhatsApp)*",
    email: "Email Address*",
    mediaSosialSutradara: "Director's Social Media",
    judulFilm: "Film Title*",
    kategoriFilm: "Film Category*",
    kategoriOptions: [
      { value: "", label: "-- Select Category --" },
      { value: "fiksi", label: "Fiction" },
      { value: "dokumenter", label: "Documentary" },
      { value: "eksperimental", label: "Experimental" },
    ],
    tahunProduksi: "Year of Production*",
    durasiFilm: "Film Duration*",
    bahasaFilm: "Language Used in the Film*",
    subtitleLink: "Subtitle Link (.srt)*",
    sinopsis: "Synopsis (max. 1000 words)*",
    pernyataanSutradara: "Director's Statement*",
    resolusiFilm: "Film Resolution*",
    resolusiOptions: [
      { value: "", label: "-- Select Resolution --" },
      { value: "Full HD", label: "Full HD" },
      { value: "2K", label: "2K" },
      { value: "4K", label: "4K" },
    ],
    sound: "Sound*",
    soundOptions: [
      { value: "", label: "-- Select Sound --" },
      { value: "mono", label: "Mono" },
      { value: "stereo", label: "Stereo" },
      { value: "silent", label: "Silent" },
    ],
    warna: "Color*",
    warnaOptions: [
      { value: "", label: "-- Select Color --" },
      { value: "warna", label: "Color" },
      { value: "hitamPutih", label: "Black & White" },
    ],
    namaProduser: "Producer's Full Name*",
    mediaSosialProduser: "Producer's Social Media",
    namaRumahProduksi: "Production House / Community*",
    mediaSosialProduksi: "Production House Social Media",
    bioSutradara: "Director Biography (max. 500 words)*",
    filmografiSutradara: "Director Filmography (PDF)*",
    submitButton: "Submit Form",
  },
};

export default texts;
