// src/utils/textsKompetisiPelajar.js
const textsKompetisiPelajar = {
  ID: {
    title: "Formulir Kompetisi Film Pelajar NTT Flobamora Film Festival 2025",
    email: "Email*",
    posisi: "Posisi yang melakukan submisi*",
    posisiOptions: {
      placeholderSelect: "-- Pilih Posisi --",
      produser: "Produser",
      sutradara: "Sutradara",
      lain: "Yang lain",
    },
    namaPendaftar: "Nama Lengkap Pendaftar*",
    nomorKontak: "Nomor Kontak Pendaftar*",
    namaSutradara: "Nama Lengkap Sutradara*",
    domisiliSutradara: "Domisili Sutradara*",
    fotoSutradara: "Foto Sutradara*",
    nomorKontakSutradara: "Nomor Kontak Sutradara*",
    emailSutradara: "Email Sutradara*",
    emailSutradaraTitle:
      "Masukkan email yang valid, misalnya: sutradara@example.com",
    mediaSosialSutradara: "Media Sosial Sutradara",
    bioSutradara: "Bio Sutradara*",
    filmografiSutradara: "Filmografi Sutradara*",
    namaProduser: "Nama Produser*",
    mediaSosialProduser: "Media Sosial Produser",
    namaSekolah: "Nama Sekolah*",
    mediaSosialSekolah: "Media Sosial Sekolah",
    kartuPelajar: "Kartu Pelajar*",
    judulFilm: "Judul Film*",
    kategoriFilm: "Kategori Film Pendek*",
    kategoriOptions: {
      fiksi: "Fiksi",
      dokumenter: "Dokumenter",
      eksperimental: "Eksperimental",
    },
    tahunProduksi: "Tahun Produksi*",
    durasiFilm: "Durasi Film*",
    bahasaFilm: "Bahasa yang digunakan di film *",
    bahasaOptions: {
      indonesia: "Bahasa Indonesia",
      inggris: "Bahasa Inggris",
      lain: "lain",
      lainLabel: "Bahasa Lain", // 👈 Ini ditampilkan di checkbox
      placeholderLain: "Tuliskan bahasa lain",
    },
    subtitleLink: "Link Subtitle (.srt)*",
    subtitleDescription:
      "Wajib menggunakan subtitle bahasa Indonesia (untuk film berdialog bahasa daerah/asing). Silakan mengisi - jika bahasa yang digunakan adalah Bahasa Indonesia",
    sinopsis: "Sinopsis Film (maks. 1000 kata)*",
    sinopsisPlaceholder: "Tuliskan sinopsis film maksimal 1000 kata",
    pernyataanSutradara: "Pernyataan Sutradara*",
    resolusiFilm: "Resolusi Film*",
    resolusiOptions: {
      placeholderSelect: "-- Pilih Resolusi --",
      fullHD: "Full HD",
      twoK: "2K",
      fourK: "4K",
    },
    sound: "Sound Film*",
    soundOptions: {
      placeholderSelect: "-- Pilih Sound --",
      mono: "Mono",
      stereo: "Stereo",
      silent: "Tanpa Suara",
    },
    warna: "Warna Film*",
    warnaOptions: {
      warna: "Warna",
      hitamPutih: "Hitam dan putih",
      keduanya: "Keduanya",
      placeholderSelect: "-- Pilih Warna --",
    },
    linkPreview: "Link Preview*",
    aksesPassword: "Akses Password (jika ada)",
    linkTrailer: "Link Trailer*",
    stillImages: "Still Images*",
    stillImagesDescription:
      "Minimal mengirimkan 3, maksimal 5 still images High Resolution. Upload maksimum 10MB per file.",
    posterFilm: "Poster Film*",
    pressKit: "Press Kit*",
    setujuPublikasiLabel:
      "Saya bersedia dan paham bahwa keseluruhan atau sebagian dari data isian formulir pendaftaran digunakan untuk keperluan publikasi dan katalog Flobamora Film Festival 2025.",
    setujuPublikasiCheckbox: "Ya, saya sepenuhnya paham.",
    publikasiFilmLabel:
      "Saya tidak berkeberatan apabila keseluruhan atau sebagian dari film yang didaftarkan dipublikasikan atau ditayangkan untuk kepentingan penyelenggaraan Flobamora Film Festival 2025.",
    publikasiFilmCheckbox: "Ya, saya sepenuhnya paham.",
    dataBenarLabel:
      "Menyatakan bahwa, data yang saya isi dalam formulir ini adalah benar dan dapat dipertanggungjawabkan.",
    dataBenarCheckbox: "Ya, saya sepenuhnya paham.",
    submitButton: "Kirim Formulir",
  },
  EN: {
    title: "Student Film Competition Form NTT Flobamora Film Festival 2025",
    email: "Email*",
    posisi: "Position of submission*",
    posisiOptions: {
      placeholderSelect: "-- Select Position --",
      produser: "Producer",
      sutradara: "Director",
      lain: "Other",
    },
    namaPendaftar: "Full Name*",
    nomorKontak: "Applicant Contact Number*",
    namaSutradara: "Director's Full Name*",
    domisiliSutradara: "Director's Residence*",
    fotoSutradara: "Director's Photo*",
    nomorKontakSutradara: "Director's Contact Number*",
    emailSutradara: "Director's Email*",
    emailSutradaraTitle:
      "Enter a valid email, for example: director@example.com",
    mediaSosialSutradara: "Director's Social Media",
    bioSutradara: "Director's Bio*",
    filmografiSutradara: "Director's Filmography*",
    namaProduser: "Producer's Name*",
    mediaSosialProduser: "Producer's Social Media",
    namaSekolah: "School Name*",
    mediaSosialSekolah: "School's Social Media",
    kartuPelajar: "Student ID Card*",
    judulFilm: "Film Title*",
    kategoriFilm: "Short Film Category*",
    kategoriOptions: {
      fiksi: "Fiction",
      dokumenter: "Documentary",
      eksperimental: "Experimental",
    },

    tahunProduksi: "Production Year*",
    durasiFilm: "Film Duration*",
    bahasaFilm: "Language used in the film *",
    bahasaOptions: {
      indonesia: "Indonesian",
      inggris: "English",
      lain: "other",
      lainLabel: "Other Language",
      placeholderLain: "Write other language",
    },
    subtitleLink: "Subtitle File (.srt)*",
    subtitleDescription:
      "Must include Indonesian subtitles (for films in local/foreign languages). You may write '-' if the film is already in Bahasa Indonesia",
    sinopsis: "Film Synopsis (max. 1000 words)*",
    sinopsisPlaceholder: "Write a film synopsis (max. 1000 words)",
    pernyataanSutradara: "Director's Statement*",
    resolusiFilm: "Film Resolution*",
    resolusiOptions: {
      placeholderSelect: "-- Select Resolution --",
      fullHD: "Full HD",
      twoK: "2K",
      fourK: "4K",
    },
    sound: "Sound Film*",
    soundOptions: {
      placeholderSelect: "-- Select Sound --",
      mono: "Mono",
      stereo: "Stereo",
      silent: "Silent",
    },
    warna: "Film Color*",
    warnaOptions: {
      warna: "Color",
      hitamPutih: "Black and White",
      keduanya: "Both",
      placeholderSelect: "-- Select Color --",
    },
    linkPreview: "Preview Link*",
    aksesPassword: "Access Password (if any)",
    linkTrailer: "Trailer Link*",
    stillImages: "Still Images*",
    stillImagesDescription:
      "Minimum 3 and maximum 5 high-resolution still images. Max 10MB per file.",
    posterFilm: "Film Poster*",
    pressKit: "Press Kit*",
    setujuPublikasiLabel:
      "I agree and understand that all or part of the registration form data will be used for publication and the Flobamora Film Festival 2025 catalog.",
    setujuPublikasiCheckbox: "Yes, I fully understand.",
    publikasiFilmLabel:
      "I have no objection if all or part of the registered film is published or screened for the purposes of organizing the Flobamora Film Festival 2025.",
    publikasiFilmCheckbox: "Yes, I fully understand.",
    dataBenarLabel:
      "I declare that the data I have filled in this form is true and accountable.",
    dataBenarCheckbox: "Yes, I fully understand.",
    submitButton: "Submit Form",
  },
};

export default textsKompetisiPelajar;
